package foo.bar;

class Test
{
  string field;
  this(uint a)
  {
    stderr::println("Test(uint): " + a);
    field = a.toString();
  }
  
  static void throwSomething()
  {
    throw new Error("Hello, Exceptions!");
  }

  static uint main([]string args)
  {
    Exception e = new Exception("AAAAA");
    final object o;
    uint i = args.length;
    while true
    {
      try
      {
        if i == 2
        {
          throw e;
        }
        try
        {
          throwSomething();
        }
        finally
        {
          stderr::println("First finally");
        }
      }
      catch Exception | Error ex
      {
        stderr::println("Caught Exception|Error: " + ex.getMessage());
      }
      catch Throwable t
      {
        stderr::println("Caught Throwable: " + t.getMessage());
      }
      finally
      {
        stderr::println("Second Finally!");
        o = new object();
      }
      stderr::println("after finally");
      break;
    }
    stderr::println("after loop");
    return 0;
  }
}
